version: "3.7"

services:
  postgres:
    container_name: mmw_postgres
    image: postgres:11.1
    restart: always
    env_file:
      - environment.env
    ports:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U custodian" ] # This shouldn't be hardcoded, fix this later
      interval: 10s
      timeout: 5s
      retries: 5

  custodian:
    container_name: custodian
    build:
      context: ./
    restart: always
    volumes:
      - "./:/app"
    env_file:
      - environment.env
    ports:
      - 80
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
