version: "3.7"

services:
  postgres:
    container_name: mmw_postgres
    image: postgres:11.1
    restart: always
    env_file:
      - environment.env
    ports:
      - 5432

  custodian:
    container_name: custodian
    build:
      context: ./
    restart: always
    env_file:
      - environment.env
    ports:
      - 80
    depends_on:
      - postgres
