import os

SECRET_TOKEN = os.environ["SECRET_TOKEN"]
TESTING_SERVERS = [os.environ["TESTING_SERVER"]]

POSTGRES_USER = os.environ["POSTGRES_USER"]
POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", 5432)
POSTGRES_DB = os.environ["POSTGRES_DB"]
DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
print(
    f"POSTGRES_USER: {POSTGRES_USER}|POSTGRES_PASSWORD: {POSTGRES_PASSWORD}|POSTGRES_HOST: {POSTGRES_HOST}|POSTGRES_PORT: {POSTGRES_PORT}|POSTGRES_DB: {POSTGRES_DB}|DATABASE_URL: {DATABASE_URL}"
)
raise Exception(DATABASE_URL)
