"""add CheckConstraint

Revision ID: 3d3808de2be6
Revises: ce1f868456e5
Create Date: 2024-03-17 03:46:15.882021

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3d3808de2be6"
down_revision: Union[str, None] = "ce1f868456e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
