"""tiebreaker default to zero instead of null

Revision ID: 93449f024e20
Revises: eff6b3cd29ae
Create Date: 2024-01-17 07:03:34.685823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93449f024e20"
down_revision: Union[str, None] = "eff6b3cd29ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initiative_members", "tiebreaker", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initiative_members", "tiebreaker", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
