"""implement init index

Revision ID: ce9ddeea95fa
Revises: 93449f024e20
Create Date: 2024-03-14 14:53:16.873319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9ddeea95fa'
down_revision: Union[str, None] = '93449f024e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative_members', sa.Column('index', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_initiative_index', 'initiative_members', ['initiative_id', 'index'])
    op.add_column('initiative_trackers', sa.Column('current_index', sa.Integer(), nullable=False))
    op.drop_column('initiative_trackers', 'current_init')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative_trackers', sa.Column('current_init', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('initiative_trackers', 'current_index')
    op.drop_constraint('unique_initiative_index', 'initiative_members', type_='unique')
    op.drop_column('initiative_members', 'index')
    # ### end Alembic commands ###
