"""implement init index

Revision ID: df01c83e0317
Revises: 93449f024e20
Create Date: 2024-03-14 16:45:34.078523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df01c83e0317'
down_revision: Union[str, None] = '93449f024e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative_trackers', sa.Column('current_index', sa.Integer(), nullable=False))
    op.drop_column('initiative_trackers', 'current_init')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiative_trackers', sa.Column('current_init', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('initiative_trackers', 'current_index')
    # ### end Alembic commands ###
