"""enforce uniqueness

Revision ID: eff6b3cd29ae
Revises: e67a85993d5e
Create Date: 2024-01-17 06:51:18.586804

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eff6b3cd29ae"
down_revision: Union[str, None] = "e67a85993d5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_initiative_member",
        "initiative_members",
        ["initiative_id", "player_name"],
    )
    op.create_unique_constraint(None, "initiative_trackers", ["channel_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "initiative_trackers", type_="unique")
    op.drop_constraint("unique_initiative_member", "initiative_members", type_="unique")
    # ### end Alembic commands ###
