name: autoformat

on:
  pull_request:
  push:
    branches: [main]

jobs:
  autoformat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      # - uses: actions/setup-python@v3
      # - uses: pre-commit/action@v3.0.1
      - uses: chartboost/ruff-action@v1
        with:
          args: "check --fix"
      - uses: chartboost/ruff-action@v1
        with:
          args: "format"
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Applying ruff format"
          default_author: github_actions
