name: autoformat

on:
  pull_request:
  push:
    branches: [main]

jobs:
  autoformat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      # - uses: actions/setup-python@v3
      # - uses: pre-commit/action@v3.0.1
      - uses: chartboost/ruff-action@v1
        with:
          args: format
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Applying ruff format
