name: Tests

on: 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
            - name: Create environment file
              run: |
                echo ${{ secrets.ENV_FILE }} > environment.env
            - name: Run tests
              run: |
                docker-compose up -d
                docker-compose exec -T custodian pytest