name: Tests

on: 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
            - name: Create environment file
              run: |
                echo SECRET_TOKEN=secrets.SECRET_TOKEN >> environment.env
                echo TESTING_SERVER=secrets.TESTING_SERVER >> environment.env
                echo POSTGRES_USER=${{ env.POSTGRES_USER }} >> environment.env
                echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> environment.env
                echo POSTGRES_DB=${{ env.POSTGRES_DB }} >> environment.env
                echo POSTGRES_HOST=${{ env.POSTGRES_HOST }} >> environment.env
                echo DUMMY_SECRET=${{ secrets.DUMMY_SECRET }} >> environment.env
                echo DUMMY_VAR=${{ vars.DUMMY_VAR }} >> environment.env
                cat environment.env
            - name: Run tests
              run: |
                docker-compose up -d
                docker-compose exec -T custodian pytest