name: Tests

on: 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
            - name: Run tests
              run: |
                docker-compose up -d
                docker-compose exec -T custodian pytest
              env:
                SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
                TESTING_SERVER: ${{ secrets.TESTING_SERVER }}
                POSTGRES_USER: ${{ vars.POSTGRES_USER }}
                POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                POSTGRES_DB: ${{ vars.POSTGRES_DB }}
                POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
